django/mackenquetes/enquetes/urls.py
from django.urls import path
from . import views

app_name = "enquetes"
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('<int:pk>/detalhes', views.DetalhesView.as_view(), name="detalhes"),
    path('<int:enquete_id>/votar', views.votar, name="votar"),
    path('<int:pk>/resultados', views.ResultadosView.as_view(), name="resultados")
]

django/mackenquetes/mackenquetes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('enquetes/', include('enquetes.urls')),
]

django/mackenquetes/enquetes/models.py
from django.db import models

# Create your models here.
class Pergunta(models.Model):
    enunciado = models.CharField(max_length=200)
    data_pub = models.DateTimeField("Data de publicação")

    def __str__(self):
        return self.enunciado

class Escolha(models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.texto

django/mackenquetes/enquetes/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.urls import reverse

from .models import Pergunta, Escolha

# Create your views here.
class IndexView(generic.ListView):
    template_name = "enquetes/index.html"
    context_object_name = "enquetes"

    def get_queryset(self):
        enquetes = Pergunta.objects.all()[:6]
        return enquetes

class DetalhesView(generic.DetailView):
    template_name = "enquetes/detalhes.html"
    model = Pergunta

def votar(request, enquete_id):
    pergunta = get_object_or_404(Pergunta, pk=enquete_id)
    try:
        escolha = pergunta.escolha_set.get(pk=request.POST['escolha'])
    except (KeyError, Escolha.DoesNotExist):
        return render(request, 'enquetes/detalhes.html', {
            'pergunta':pergunta,
            'erro':'Você não selecionou uma opção.',
        })
    
    escolha.votos += 1
    escolha.save()
    return HttpResponseRedirect(reverse('enquetes:resultados', args=(pergunta.id,)))

class ResultadosView(generic.DetailView):
    template_name = "enquetes/resultados.html"
    model = Pergunta

django/mackenquetes/enquetes/templates/enquetes/detalhes.html
{% load static %}

<!DOCTYPE html>
<html>

	<head>
		<title>MackEnquetes</title>
		<link rel="stylesheet" type="text/css" href="{% static 'enquetes/style_detalhes.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'enquetes/setup.css' %}">
		<link rel="shortcut icon" href="{% static 'enquetes/img/favicon.ico' %}">

	</head>
	<body>
		<header class="title_cont">
			<article class="title">
				<h1>MackEnquetes</h1>
			</article>
			<article>
				<h1 class="m">/ M /</h1>
			</article>
		</header>

		<section class="outter">
			<article class="title">
				<h2> - Enquetes - </h2>
			</article>
			<section class="formm_cont">
				<article>
					{% if erro %}
						<article class="erro">
							<p> <strong>{{ erro }}</strong></p>
						</article>
					{% endif %}
					<section class="formm">
						<article>
							<h3> {{ pergunta.enunciado }} </h3>
							<form action="{% url 'enquetes:votar' pergunta.id %}" method="post">
								{% csrf_token %}
								{% for escolha in pergunta.escolha_set.all %}
									<article class="boxes">
									    <input type="radio" name="escolha" id="escolha{{ forloop.counter }}" value="{{ escolha.id }}">
									    <label for="escolha{{ forloop.counter }}">{{ escolha.texto }}</label>
									</article>
								{% endfor %}

								<input type="submit" value="Votar">

							</form>
						</article>
					</section>
				</article>
			</section>
			<section class="return">
				<a href="{% url 'enquetes:index' %}">Voltar</a>
			</section>

			<footer>
				<article>
					<p>Powered by</p>
					<i class="faz">FAZ O WHILE</i>
				</article>
			</footer>
		</section>

	</body>
</html>

django/mackenquetes/enquetes/templates/enquetes/index.html
{% load static %}

<!DOCTYPE html>
<html>

	<head>
		<title>MackEnquetes</title>
		<link rel="stylesheet" type="text/css" href="{% static 'enquetes/style_index.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'enquetes/setup.css' %}">
		<link rel="shortcut icon" href="{% static 'enquetes/img/favicon.ico' %}">

	</head>
	<body>
		<header class="title_cont">
			<article class="title">
				<h1>MackEnquetes</h1>
			</article>
			<article>
				<h1 class="m">/ M /</h1>
			</article>
		</header>

		<section class="inner">
			<article class="title">
				<h2> - Enquetes -</h2>
			</article>
			<article>

				{% if enquetes %}
				    <ul>
			        	<li>
			        		{% for enquete in enquetes %}
			        			<a href="{% url 'enquetes:detalhes' enquete.id %}">{{ enquete.enunciado }}</a>
			        		{% endfor %}
			        	</li>					        
				    </ul>
				{% else %}

					<section class="blank_cont">
					    <section class="blank_cc">
					    	<article class="blank"></article>
					    	<article class="sorry">
					    		<p>Desculpe, mas estamos sem perguntas ...</p>
					    	</article>
					    </section>
				   	</section>
				{% endif %}
			</article>
		</section>
		<footer>
			<article>
				<p>Powered by</p>
				<i class="faz">FAZ O WHILE</i>
			</article>
		</footer>
	</body>
</html>

django/mackenquetes/enquetes/templates/enquetes/resultados.html
{% load static %}
<!DOCTYPE html>
<html>

	<head>
		<title>MackEnquetes</title>
		<link rel="stylesheet" type="text/css" href="{% static 'enquetes/style_resultado.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'enquetes/setup.css' %}">
		<link rel="shortcut icon" href="{% static 'enquetes/img/favicon.ico' %}">

	</head>
	<body>
		<header class="title_cont">
			<article class="title">
				<h1>MackEnquetes</h1>
			</article>
			<article>
				<h1 class="m">/ M /</h1>
			</article>
		</header>
		<section class="outter">
				<article class="title">
					<div>
						<h2>  {{ pergunta.enunciado }} </h2>
						<h3> Resultados </h3>
					</div>
				</article>
				<article class="results">
					<ul>
						{% for escolha in pergunta.escolha_set.all %}
						    <li>
						    	<p> {{ escolha.texto }} </p> 
						    	<p> Votos : {{ escolha.votos }} </p>
						    </li>
						{% endfor %}
					</ul>
				</article>
				<section class="return">
					<a href="{% url 'enquetes:index' %}">Voltar</a>
				</section>
				<footer>
					<article>
						<p>Powered by</p>
						<i class="faz">FAZ O WHILE</i>
					</article>
				</footer>
		</section>
	</body>
</html>