flask/enquetes/models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from flask_login import UserMixin

from app import db

class Pergunta(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    enunciado = db.Column(db.String(200), unique=True, nullable=False)
    data_pub = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    escolha = db.relationship('Escolha', backref='pergunta', cascade="all,delete", lazy=False)

    def __repr__(self):
        return '<Pergunta %r>' % self.enunciado

    def __str__(self):
        return self.enunciado

class Escolha(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    texto = db.Column(db.String(200), nullable=False)
    votos = db.Column(db.Integer, default=0)

    pergunta_id = db.Column(db.Integer, db.ForeignKey('pergunta.id'), nullable=False)

    def __repr__(self):
        return '<Escolha %r, Votos %r>' % (self.texto, self.votos)

class Usuario(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    usuario = db.Column(db.String(15), unique=True, nullable=False)
    senha = db.Column(db.String(20), unique=True, nullable=False)

    def __repr__(self):
        return '<Usuario %r, Senha%r>' % (self.usuario, self.senha)

flask/app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import  LoginManager
from flask_admin import Admin


db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    
    app.config['SECRET_KEY'] = "randomstring"
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
    db.init_app(app)

    from enquetes.views import enquetes, NewAdminIndexView, NewModelView, PerguntaModelView
    app.register_blueprint(enquetes)

    #Registra admin
    from enquetes.models import Usuario, Pergunta, Escolha
    login = LoginManager(app)

    @login.user_loader
    def load_user(user_id):
        return Usuario.query.get(user_id)

    admin = Admin(app, index_view=NewAdminIndexView())
    admin.add_view(PerguntaModelView(Pergunta, db.session))
    admin.add_view(NewModelView(Escolha, db.session))
    admin.add_view(NewModelView(Usuario, db.session))

    return app

if __name__ == "__main__":
    app = create_app()
    app.run(debug=True)

flask/enquetes/views.py
from flask import Flask, request, flash, url_for, redirect, render_template, Blueprint
from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView
from flask_login import current_user, login_user, logout_user

from .models import Usuario, Pergunta, Escolha
from app import db

enquetes = Blueprint('enquetes', __name__, url_prefix='/enquetes')

class NewModelView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated
    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('enquetes.login'))

class PerguntaModelView(ModelView):
    inline_models = (Escolha,)
    
class NewAdminIndexView(AdminIndexView):
    def is_accessible(self):
        return current_user.is_authenticated
    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('enquetes.login'))


@enquetes.route('/')
def index():
   return render_template('enquetes/index.html', enquetes=Pergunta.query.all())

@enquetes.route('/resultados/<int:pergunta_id>')
def resultados(pergunta_id):
   return render_template('enquetes/resultados.html', pergunta=Pergunta.query.get_or_404(pergunta_id))

@enquetes.route('/detalhes/<int:pergunta_id>', methods=['GET', 'POST'])
def detalhes(pergunta_id):
    if request.method == 'POST':
        if not request.form.get('escolha'):
            flash('Escolha uma opção')
        else:
            escolha = Escolha.query.filter_by(id=request.form['escolha']).first()
            escolha.votos = escolha.votos + 1
            db.session.commit()

            return redirect(url_for('enquetes.resultados', pergunta_id=pergunta_id))

    return render_template('enquetes/detalhes.html', pergunta=Pergunta.query.get_or_404(pergunta_id))

@enquetes.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        if not request.form['usuario'] or not request.form['senha']:
           flash('Digite o Usuário e a Senha')

        else:
            exists = db.session.query(db.exists().where(Usuario.usuario == request.form['usuario'] )).scalar()

            if exists:
                usuario = Usuario.query.filter_by(usuario=request.form['usuario']).first()
                if usuario.senha ==  request.form['senha']:

                    login_user(usuario)
                    return redirect(url_for('admin.index'))
                else:
                    flash('Usuário desconhecido ou senha incorreta')
            else:
                flash('Usuário desconhecido ou senha incorreta')

    return render_template('enquetes/login.html')

@enquetes.route('/logout')
def logout():
    logout_user()
    return render_template('enquetes/logout.html')

flask/views.py
from flask import Flask, request, flash, url_for, redirect, render_template
from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView
from flask_login import  LoginManager, current_user, login_user, logout_user

from db import *
from enquete_app import app


login = LoginManager(app)

@login.user_loader
def load_user(user_id):
    return Usuario.query.get(user_id)

class NewModelView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated
    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('login'))
    
class NewAdminIndexView(AdminIndexView):
    def is_accessible(self):
        return current_user.is_authenticated
    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('login'))

admin = Admin(app, index_view=NewAdminIndexView())
admin.add_view(NewModelView(Pergunta, db.session))
admin.add_view(NewModelView(Escolha, db.session))
admin.add_view(NewModelView(Usuario, db.session))



@app.route('/')
def index():
   return render_template('index.html', enquetes=Pergunta.query.all())

@app.route('/resultados/<int:pergunta_id>')
def resultados(pergunta_id):
   return render_template('resultados.html', pergunta=Pergunta.query.get_or_404(pergunta_id))

@app.route('/detalhes/<int:pergunta_id>', methods=['GET', 'POST'])
def detalhes(pergunta_id):
    if request.method == 'POST':
        if not request.form.get('escolha'):
            flash('Escolha uma opção')
        else:
            escolha = Escolha.query.filter_by(id=request.form['escolha']).first()
            escolha.votos = escolha.votos + 1
            db.session.commit()

            return redirect(url_for('resultados', pergunta_id=pergunta_id))

    return render_template('detalhes.html', pergunta=Pergunta.query.get_or_404(pergunta_id))

@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        if not request.form['usuario'] or not request.form['senha']:
           flash('Digite o Usuário e a Senha')

        else:
            exists = db.session.query(db.exists().where(Usuario.usuario == request.form['usuario'] )).scalar()

            if exists:
                usuario = Usuario.query.filter_by(usuario=request.form['usuario']).first()
                if usuario.senha ==  request.form['senha']:

                    login_user(usuario)
                    return redirect(url_for('admin.index'))
                else:
                    flash('Usuário desconhecido ou senha incorreta')
            else:
                flash('Usuário desconhecido ou senha incorreta')

    return render_template('login.html')

@app.route('/logout')
def logout():
    logout_user()
    return render_template('logout.html')

flask/templates/enquetes/detalhes.html
<!DOCTYPE html>
<html lang="pt-br">

	<head>
		<title>MackEnquetes</title>
		<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='../../static/style_detalhes.css')}}">
		<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='../../static/setup.css')}}">
		<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='../../static/img/favicon.ico')}}">
		<meta charset="utf-8">

	</head>
	<body>
		<header class="title_cont">
			<article class="title">
				<h1>MackEnquetes</h1>
			</article>
			<article>
				<h1 class="m">/ M /</h1>
			</article>
		</header>

		<section class="outter">
			<article class="title">
				<h2> - Enquetes - </h2>
			</article>
			<section class="formm_cont">
				<article>
					{%- for category, message in get_flashed_messages(with_categories = true) %}

						<article class="erro">
							<p> <strong>{{ message }}</strong></p>
						</article>
					{%- endfor %}
					<section class="formm">
						<article>
							<h3> {{ pergunta }}</h3>
							<form action = "{{ request.path }}" method = "POST">
								{% for escolha in pergunta.escolha %}
									<article class="boxes">
									    <input type="radio" name="escolha" id="escolha{{ loop.index }}" value="{{ escolha.id }}">
									    <label for="escolha{{ loop.index }}">{{ escolha.texto }}</label>
									</article>
								{% endfor %}

								<input type="submit" value="Votar">

							</form>				
						</article>
					</section>
				</article>
			</section>
			<section class="return">
				<a href="{{ url_for('enquetes.index') }}">Voltar</a>
			</section>

			<footer>
				<article>
					<p>Powered by</p>
					<i class="faz">FAZ O WHILE</i>
				</article>
			</footer>
		</section>
	</body>
</html>

flask/templates/enquetes/index.html
<!DOCTYPE html>
<html lang="pt-br">

	<head>
		<title>MackEnquetes</title>
		<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='../../static/style_index.css')}}">
		<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='../../static/setup.css')}}">
		<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='../../static/img/favicon.ico')}}">
		<meta charset="utf-8">

	</head>
	<body>
		<header class="title_cont">
			<article class="title">
				<h1>MackEnquetes</h1>
			</article>
			<article>
				<h1 class="m">/ M /</h1>
			</article>
		</header>

		<section class="inner">
			<article class="title">
				<h2> - Enquetes -</h2>
			</article>
			<article>
				{% if enquetes %}
				    <ul>
				    	<li>
				    		{% for enquete in enquetes %}
				    			<a href="{{ url_for('enquetes.detalhes', pergunta_id=enquete.id) }}">{{ enquete.enunciado}}</a>
							{% endfor %}				    	
				    	</li>
				    </ul>
				{% else %}

					<section class="blank_cont">
					    <section class="blank_cc">
					    	<article class="blank"></article>
					    	<article class="sorry">
					    		<p>Desculpe, mas estamos sem perguntas ...</p>
					    	</article>
					    </section>
				   	</section>
				{% endif %}
			</article>
		</section>
		<footer>
			<article>
				<p>Powered by</p>
				<i class="faz">FAZ O WHILE</i>
			</article>
		</footer>
	</body>
</html>			    		

flask/templates/enquetes/login.html
<!DOCTYPE html>
<html lang="pt-br">

	<head>
		<title>MackEnquetes</title>
		<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='../../static/style_login.css')}}">
		<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='../../static/img/favicon.ico')}}">
		<meta charset="utf-8">

	</head>
	<body>
		<section class="outter">
			<article>
				<h3><i> Admin Login</i> </h3>
				<form action = "{{ request.path }}" method = "post">
					<input type = "text" name = "usuario" placeholder="Usuário"/><br>
					<input type = "password" name = "senha" placeholder="Senha" /><br>
					<input type = "submit" value = "Submit"  class="submit" />
				</form>
			  	{%- for category, message in get_flashed_messages(with_categories = true) %}
			        <div class="erro">
			        	{{ message }}
			    	</div>
			    {%- endfor %}
			</article>
		</section>
	</body>
</html>

flask/templates/enquetes/logout.html
<!DOCTYPE html>
<html lang="pt-br">

	<head>
		<title>MackEnquetes</title>
		<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='../../static/style_login.css')}}">
		<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='../../static/img/favicon.ico')}}">
		<meta charset="utf-8">

	</head>
	<body>
		<section class="outter">
			<article>
				<h3><i>Usuário Desconectado </i></h3>
				<p>Até a próxima!</p>
			</article>
			<section class="return">
				<a href="{{ url_for('enquetes.index') }}">Voltar</a>
			</section>
		</section>
	</body>
</ht

flask/templates/enquetes/resultados.html
<!DOCTYPE html>
<html lang="pt-br">

	<head>
		<title>MackEnquetes</title>
		<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='../../static/style_resultado.css')}}">
		<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='../../static/setup.css')}}">
		<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='../../static/img/favicon.ico')}}">
		<meta charset="utf-8">

	</head>
	<body>
		<header class="title_cont">
			<article class="title">
				<h1>MackEnquetes</h1>
			</article>
			<article>
				<h1 class="m">/ M /</h1>
			</article>
		</header>
		<section class="outter">
				<article class="title">
					<div>
						<h2>  {{ pergunta }} </h2>
						<h3> Resultados </h3>
					</div>
				</article>
				<article class="results">
					<ul>
						{% for escolha in pergunta.escolha %}
						    <li>
						    	<p> {{ escolha.texto }} </p> 
						    	<p> Votos : {{ escolha.votos }} </p>
						    </li>
						{% endfor %}
					</ul>
				</article>
				<section class="return">
					<a href="{{ url_for('enquetes.index') }}">Voltar</a>
				</section>
				<footer>
					<article>
						<p>Powered by</p>
						<i class="faz">FAZ O WHILE</i>
					</article>
				</footer>
		</section>
	</body>
</html>

flask/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>MackEnquetes</title>
    <meta charset="utf-8">
  </head>
  <body>
    {% if enquetes %}
      <ul>
          {% for enquete in enquetes %}
          <li><a href = "{{ url_for('detalhes', pergunta_id=enquete.id) }}">{{ enquete.enunciado }}</a></li>
          {% endfor %}
      <ul>
    {% else %}
      <p>Não há enquetes para mostrar.</p>
    {% endif %} 
  </body>
</html>